### ISSUE TITLE
[Question] How to make the command be called every time you type something. 

### ISSUE THREAD

**Issue by manudss** [slapdash/platform#12]
This is the case for the unsplash command. Which makes a new search each time you keep typing. 
But in my case, it doesn't work. It only retrieves the first letter, and as soon as you return results, it doesn't call the command again. And subsequent searches are only done in the first list of results. 

But I need to redo the search each time, because the results are refined according to the search. How to do this. I don't see any information in the documentation. 

Thanks in advance.

**Comment by taras-slapdash** [comment]
Hey @manudss!

Thank you for writing in. And sorry for the inconvinience and poor documentation on our side. We'll fix it.
﻿
Right now, there is a [`ranking` property for List View](https://platform.slapdash.com/reference/command-response-view-list) that allows you to choose whether you want to use the built-in ranking or you want to completely control it yourself. It's just a boolean but the idea was to extend it and allow you to have more granular control over ranking. 

If you set `ranking` to `false` Slapdash won't use its ranking and your command will be run **whenever the input changes**. This way you can fully control what options and how many of them are returned. The downside is that your command will be responsible for performing the search and Slapdash won't display the matches (highlight matched characters).﻿﻿
﻿
I hope this explanation is helpful but please let us know if you have any additional questions or feedback.

**Comment by manudss** [comment]
Thanks, for the answer. 

I was able to make it works.
