### ISSUE TITLE
Unable to make Alt+Space shortcut

### ISSUE THREAD

**Issue by Merloss** [slapdash/platform#5]
I'm attempting to add an alt+space shortcut but am unable to do so, as shown in the image below.

![image](https://user-images.githubusercontent.com/54235902/151414729-b7b76c59-6054-447d-a7ea-716418e629fe.png)

**Comment by oleg-slapdash** [comment]
@Merloss, Is it possible that you have something else (e.g. Spotlight) set up as a shortcut? For example Spotlight?

<img width="780" alt="Screen Shot 2022-01-27 at 13 07 49" src="https://user-images.githubusercontent.com/73438352/151418293-c83ceaa2-5462-4515-9bc3-03aef4a04728.png">

You can always reach out to us via chat or via hello@slapdash.com if you need more product-specific help.

**Comment by Merloss** [comment]
No, I don't have any other apps installed. I removed the default Windows shortcut because I assumed it was incompatible with the windows shortcut, but I still can't use it.

![image](https://user-images.githubusercontent.com/54235902/151418832-e8b792d0-9df5-4624-830e-f4923b7eed47.png)

**Comment by oleg-slapdash** [comment]
I see, I don't see an easy way to remove the default windows shortcut for Alt+Tab. However, I think I have a workaround for you: You can install https://github.com/microsoft/PowerToys from Microsoft that allows you to re-map the shortcuts and simply remap the "alt space" to "ctrl j":
<img width="600" alt="Screen Shot 2022-01-27 at 14 32 49" src="https://user-images.githubusercontent.com/73438352/151430858-82f550c6-63df-414d-be49-9214ccd86f25.png">

**Comment by Merloss** [comment]
Thank you, this is also a solution.
