### ISSUE TITLE
Feature request: more flexibility on script extensions

### ISSUE THREAD

**Issue by pomdtr** [slapdash/platform#6]
Since slapdash is able to run any script based on it's shebang, I don't think that the requirements on a specific file extension is necessary.

I want to build a local command using [zx](https://github.com/google/zx), which is based on `.mjs` scripts.
I currently need to either:
- switch to a `.js` extension, but I loose top level async
- switch to a `.sh` extension as demonstrated [here](https://github.com/slapdash/platform/blob/main/templates/custom-shebang-not-bash.sh), but I loose syntax highlighting and code completion (unless I do additional file association setup)

**Comment by taras-slapdash** [comment]
Hey @pomdtr, thanks for your suggestion! 

To make everything simpler, Slapdash tries to automatically detect the runner for your script. If shebang is present, we use it to locate the binary and if not, we rely on the file extension as a hint to find the right runner. You can read more about this process in [our docs](https://platform.slapdash.com/command-bar-101/local-commands#locating-language-binaries).

While this automatic runner detection approach works in the majority of the cases, it can be limiting.

Here is what I think we're going to do:

1. In the short term, we'll add `.mjs` as a recognised file extension for `node`. We'll let you know once it's released.
2. In the long term, we'll look into adding controls for developers to override the runner. We'll still automatically detect the runner based on the file you selected but then you'll be able to override it by choosing a different binary.

**Comment by zuta** [comment]
@pomdtr, sorry for the delay.

Starting from v2.9 you should be able to create a Local Command using an `.mjs` script.

Let us know if you run into any issues.

**Comment by taras-slapdash** [comment]
@pomdtr, sorry for the delay.

Starting from v2.9 you should be able to create a Local Command using an `.mjs` script.

Let us know if you run into any issues.

**Comment by taras-slapdash** [comment]
I'm going to close this issue as there is a workaround and we track the broader change internally. Do file a new issue in case you have another feature request or a question.
